### ISSUE TITLE
Closing `:` is not reported as `punctuation.definition.interpreted.sphinx`

### ISSUE THREAD

**Issue by Bobronium** [leonhard-s/python-sphinx-highlighter#8]
In source code, I see that tag: meant to have 3 groups, however for some reason third (closing :) is not reported as a sphinx scope:
```yml
  tag:
    # RST inline tags. These are mostly used for autodoc tags, i.e.
    # things like ":param key:" or ":rtype: str".
    match: (:)(${{ alpha }}[${{ alphaNum }} _\-\.\*\\]+?${{ alphaNum }}(\?_)?)(:)(?!`)
    captures:
      1: { name: punctuation.definition.interpreted.sphinx }
      2: { name: entity.name.tag.sphinx }
      3: { name: punctuation.definition.interpreted.sphinx }
```

<img width="695" alt="image" src="https://user-images.githubusercontent.com/36469655/168851188-0631faa2-f1a6-484d-a14f-1e3b0ed35779.png">
